version: '3.1'

networks:
  hcu:

services:
  cassandra:
    container_name: hcu-cassandra-server
    image: cassandra
    ports:
      - "9042:9042"
    networks:
      - hcu

  mysql:
    image: mysql
    container_name: hcu-mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mservicepwd
    ports:
      - '3306:3306'
    networks:
      - hcu

  elasticsearch:
    image: elasticsearch:7.17.5
    container_name: hcu-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks:
      - hcu

  msrabbitmq:
    image: rabbitmq:3-management
    container_name: hcu-msrabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=hcurabbit
      - RABBITMQ_DEFAULT_PASS=hcurabbit
    networks:
      - hcu

# Local Services -----------------------

  hcu-account-service:
    image: account-service:10.0.1
    container_name: hcu-account-service
    restart: always
    networks:
      - hcu
    environment:
      CONFIG_SERVER_URL: http://hcu-config-server:8888
      CASSANDRA_SERVER_HOST: hcu-cassandra-server
      SERVER_PORT: 8080
    ports:
      - '8080:8080'

  hcu-ticket-service:
    image: ticket-service:0.0.1-SNAPSHOT
    container_name: hcu-ticket-service
    restart: always
    networks:
      - hcu
    environment:
      CONFIG_SERVER_URL: http://hcu-config-server:8888
      SERVER_PORT: 8080
    ports:
      - '8080:8080'

  hcu-notification-service:
    image: notification-service:0.0.1-SNAPSHOT
    container_name: hcu-notification-service
    restart: always
    networks:
      - hcu
    environment:
      CONFIG_SERVER_URL: http://hcu-config-server:8888
      SERVER_PORT: 8080
    ports:
      - '8080:8080'

  # System Services -----------------------

  hcu-config-server:
    image: config-server:0.0.1-SNAPSHOT
    container_name: hcu-config-server
    restart: always
    networks:
      - hcu
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      SERVER_PORT: 8888
    ports:
      - '8888:8888'

  hcu-eureka-server:
    image: eureka-server:0.0.1-SNAPSHOT
    container_name: hcu-eureka-server
    restart: always
    networks:
      - hcu
    environment:
      CONFIG_SERVER_URL: http://hcu-config-server:8888
      SERVER_PORT: 8887
    ports:
      - '8887:8887'

  hcu-admin-server:
    image: admin-server:0.0.1-SNAPSHOT
    container_name: hcu-admin-server
    restart: always
    networks:
      - hcu
    environment:
      EUREKA_SERVICE_URL: http://hcu-eureka-server:8888
      SERVER_PORT: 8886
    ports:
      - '8886:8886'

  hcu-gateway-server:
    image: gateway-server:0.0.1-SNAPSHOT
    container_name: hcu-gateway-server
    restart: always
    networks:
      - hcu
    environment:
      EUREKA_SERVICE_URL: http://hcu-eureka-server:8888
      SERVER_PORT: 8885
    ports:
      - '8885:8885'

  hcu-hystrix-dashboard:
    image: hystrix-dashboard:0.0.1-SNAPSHOT
    container_name: hcu-hystrix-dashboard
    restart: always
    networks:
      - hcu
    environment:
      EUREKA_SERVICE_URL: http://hcu-eureka-server:8888
      SERVER_PORT: 8884
    ports:
      - '8884:8884'

  hcu-zipkin-server:
    image: zipkin-server:0.0.1-SNAPSHOT
    container_name: hcu-zipkin-server
    restart: always
    networks:
      - hcu
    environment:
      EUREKA_SERVICE_URL: http://hcu-eureka-server:8888
      SERVER_PORT: 8883
    ports:
      - '8883:8883'