version: '3.1'

networks:
  hcu:

services:
  hcu-cassandra-server:
    container_name: hcu-cassandra-server
    image: cassandra
    ports:
      - "9042:9042"
    networks:
      - hcu

  hcu-mysql-server:
    image: mysql
    container_name: hcu-mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mservicepwd
    ports:
      - '3306:3306'
    networks:
      - hcu

  hcu-elasticsearch:
    image: elasticsearch:7.17.5
    container_name: hcu-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks:
      - hcu

  hcu-msrabbitmq:
    image: rabbitmq:3-management
    container_name: hcu-msrabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=hcurabbit
      - RABBITMQ_DEFAULT_PASS=hcurabbit
    networks:
      - hcu

# Local Services -----------------------

  hcu-account-service:
    image: hcu/account-service:0.0.1-SNAPSHOT
    container_name: hcu-account-service
    restart: always
    networks:
      - hcu
    environment:
      CONFIG_SERVER_URL: http://hcu-config-server:8888
      ZIPKIN_SERVER_URL: http://hcu-zipkin-server:8883
      EUREKA_SERVER_URL: http://hcu-eureka-server:8887/eureka/
      CASSANDRA_SERVER_HOST: hcu-cassandra-server
      SERVER_PORT: 8080
    ports:
      - '8081:8080'
    depends_on:
      - hcu-config-server
      - hcu-cassandra-server

  hcu-ticket-service:
    image: hcu/ticket-service:0.0.1-SNAPSHOT
    container_name: hcu-ticket-service
    restart: always
    networks:
      - hcu
    environment:
      CONFIG_SERVER_URL: http://hcu-config-server:8888
      ZIPKIN_SERVER_URL: http://hcu-zipkin-server:8883
      EUREKA_SERVER_URL: http://hcu-eureka-server:8887/eureka/
      MYSQL_URL: jdbc:mysql://hcu-mysql-server:3306/ticket_service
      ELASTICSEARCH_URL: http://hcu-elasticsearch:9200
      RABBITMQ_HOST: hcu-msrabbitmq
      SERVER_PORT: 8080
    ports:
      - '8082:8080'
    depends_on:
      - hcu-config-server
      - hcu-mysql-server
      - hcu-elasticsearch
      - hcu-msrabbitmq

  hcu-notification-service:
    image: hcu/notification-service:0.0.1-SNAPSHOT
    container_name: hcu-notification-service
    restart: always
    networks:
      - hcu
    environment:
      CONFIG_SERVER_URL: http://hcu-config-server:8888
      ZIPKIN_SERVER_URL: http://hcu-zipkin-server:8883
      EUREKA_SERVER_URL: http://hcu-eureka-server:8887/eureka/
      RABBITMQ_HOST: hcu-msrabbitmq
      SERVER_PORT: 8080
    ports:
      - '8083:8080'
    depends_on:
      - hcu-config-server
      - hcu-msrabbitmq

  # System Services -----------------------

  hcu-config-server:
    image: hcu/config-server:0.0.1-SNAPSHOT
    container_name: hcu-config-server
    restart: always
    networks:
      - hcu
    environment:
      SERVER_PORT: 8888
    ports:
      - '8888:8888'

  hcu-eureka-server:
    image: hcu/eureka-server:0.0.1-SNAPSHOT
    container_name: hcu-eureka-server
    restart: always
    networks:
      - hcu
    environment:
      SERVER_PORT: 8887
      ZIPKIN_SERVER_URL: http://hcu-zipkin-server:8883
      SPRING_BOOT_ADMIN_SERVER_URL: http://hcu-admin-server:8886
      EUREKA_SERVER_URL: http://hcu-eureka-server:8887/eureka/
      CONFIG_SERVER_URL: http://hcu-config-server:8888
      EUREKA_SERVER_HOST: hcu-eureka-server
    ports:
      - '8887:8887'
    depends_on:
      - hcu-config-server

  hcu-admin-server:
    image: hcu/admin-server:0.0.1-SNAPSHOT
    container_name: hcu-admin-server
    restart: always
    networks:
      - hcu
    environment:
      EUREKA_SERVICE_URL: http://hcu-eureka-server:8887/eureka/
      SERVER_PORT: 8886
    ports:
      - '8886:8886'
    depends_on:
      - hcu-eureka-server

  hcu-gateway-server:
    image: hcu/gateway-server:0.0.1-SNAPSHOT
    container_name: hcu-gateway-server
    restart: always
    networks:
      - hcu
    environment:
      EUREKA_SERVICE_URL: http://hcu-eureka-server:8887
      SERVER_PORT: 8885
    ports:
      - '8885:8885'
    depends_on:
      - hcu-eureka-server

  hcu-hystrix-dashboard:
    image: hcu/hystrix-dashboard:0.0.1-SNAPSHOT
    container_name: hcu-hystrix-dashboard
    restart: always
    networks:
      - hcu
    environment:
      EUREKA_SERVICE_URL: http://hcu-eureka-server:8887
      SERVER_PORT: 8884
    ports:
      - '8884:8884'
    depends_on:
      - hcu-eureka-server

  hcu-zipkin-server:
    image: hcu/zipkin-server:0.0.1-SNAPSHOT
    container_name: hcu-zipkin-server
    restart: always
    networks:
      - hcu
    environment:
      EUREKA_SERVICE_URL: http://hcu-eureka-server:8887/eureka/
      SERVER_PORT: 8883
    ports:
      - '8883:8883'
    depends_on:
      - hcu-eureka-server