version: '3.1'
services:
  cassandra:
    container_name: cassdb
    image: cassandra
    ports:
      - "9042:9042"
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mservicepwd
    ports:
      - '3306:3306'
  elasticsearch:
    image: elasticsearch:7.17.5
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
