server:
  port: 8501

spring:
  application:
    name: account-service

spcloud:
  cassandra:
    contact:
      point: localhost
    port : 9042
    keyspace:
      name: spring_cloud
    username : cassandra
    password : cassandra