server:
  port: 8501

spring:
  application:
    name: account-service
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

spcloud:
  cassandra:
    contact:
      point: localhost
    port: 9042
    keyspace:
      name: spring_cloud
    username: cassandra
    password: cassandra