server:
  port: ${SERVER_PORT:8501}

spring:
  application:
    name: account-service
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spcloud:
  cassandra:
    contact:
      point: ${CASSANDRA_SERVER_HOST:localhost}
    port: ${CASSANDRA_SERVER_PORT:9042}
    keyspace:
      name: ${CASSANDRA_SERVER_KEYSPACE:spring_cloud}
    username: ${CASSANDRA_SERVER_USERNAME:cassandra}
    password: ${CASSANDRA_SERVER_PASSWORD:cassandra}