server:
  port: ${SERVER_PORT:8503}

spring:
  application:
    name: notification-service
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
  rabbitmq:
    username: ${RABBITMQ_USERNAME:hcurabbit}
    password: ${RABBITMQ_PASSWORD:hcurabbit}
    host: ${RABBITMQ_HOST:localhost}
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"