server:
  port: ${SERVER_PORT:8502}

spring:
  application:
    name: ticket-service
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/ticket_service}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:mservicepwd}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: ${RABBITMQ_USERNAME:hcurabbit}
    password: ${RABBITMQ_PASSWORD:hcurabbit}
    host: ${RABBITMQ_HOST:localhost}
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue
  elasticsearch:
    uris: ${ELASTICSEARCH_URL:localhost:9200}

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"